---

- name: 'Generate xml from schema and value.'
  template:
    attributes: '{{ attributes }}'
    backup: '{{ backup }}'
    dest: '{{ dest }}'
    follow: '{{ follow }}'
    force: '{{ force }}'
    group: '{{ group }}'
    header: '{{ header }}'
    mode: '{{ mode }}'
    newline_sequence: '{{ newline_sequence }}'
    owner: '{{ owner }}'
    selevel: '{{ selevel }}'
    serole: '{{ serole }}'
    setype: '{{ setype }}'
    seuser: '{{ seuser }}'
    src: 'xml.j2'
    trim_blocks: false
    unsafe_writes: '{{ unsafe_writes }}'
  when:
    - 'dest is defined and dest is string'
    - 'schema is defined and schema is mapping'
    - 'value is defined and value is mapping'
