---

- name: 'Debug vars'
  block:
    - name: 'schema:'
      debug:
        msg: '{{ lookup("vars","schema",default={})|to_yaml|indent(2,true) }}'
    - name: 'value:'
      debug:
        msg: '{{ lookup("vars","value",default={})|to_yaml|indent(2,true) }}'
  when: 'debug|default(false)'

- name: 'Stat dest xml file.'
  changed_when: false
  register: 'before'
  stat:
    get_attributes: false
    get_mime: false
    path: '{{ dest }}'
  when: 'notify is defined'

- name: 'Generate xml from schema and value.'
  changed_when: false  # Use stat to measure change.
  template:
    attributes: '{{ attributes|default(omit) }}'
    backup: '{{ backup|default(omit) }}'
    dest: '{{ dest }}'
    follow: '{{ follow|default(omit) }}'
    force: '{{ force|default(omit) }}'
    group: '{{ group|default(omit) }}'
    mode: '{{ mode|default(omit) }}'
    newline_sequence: '{{ newline_sequence|default(omit) }}'
    owner: '{{ owner|default(omit) }}'
    selevel: '{{ selevel|default(omit) }}'
    serole: '{{ serole|default(omit) }}'
    setype: '{{ setype|default(omit) }}'
    seuser: '{{ seuser|default(omit) }}'
    src: 'xml.j2'
    trim_blocks: false
    unsafe_writes: '{{ unsafe_writes|default(omit) }}'
  when:
    - 'dest is defined and dest is string'
    - 'schema is defined and schema is mapping'
    - 'value is defined and value is mapping'

- name: 'Stat dest xml file again.'
  register: 'after'
  changed_when: 'after.stat.checksum != before.stat.checksum|default("")'
  notify: '{{ notify|default(omit) }}'
  stat:
    get_attributes: false
    get_mime: false
    path: '{{ dest }}'
  when: 'notify is defined'
