---

- block:

    - name: 'Generate xml from schema and value.'
      template:
        attributes: '{{ attributes|default(omit) }}'
        backup: '{{ backup|default(omit) }}'
        dest: '{{ dest }}'
        follow: '{{ follow|default(omit) }}'
        force: '{{ force|default(omit) }}'
        group: '{{ group|default(omit) }}'
        mode: '{{ mode|default(omit) }}'
        newline_sequence: '{{ newline_sequence|default(omit) }}'
        owner: '{{ owner|default(omit) }}'
        selevel: '{{ selevel|default(omit) }}'
        serole: '{{ serole|default(omit) }}'
        setype: '{{ setype|default(omit) }}'
        seuser: '{{ seuser|default(omit) }}'
        src: 'xml.j2'
        trim_blocks: false
        unsafe_writes: '{{ unsafe_writes|default(omit) }}'
      when:
        - 'dest is defined and dest is string'
        - 'schema is defined and schema is mapping'
        - 'value is defined and value is mapping'

  rescue:

    - name: 'Error evaluating xml.j2 template; inspect args'
      debug:
        msg: '{{ varname }}: {{ lookup("vars",varname)|to_yaml }}'
      loop:
        - 'dest'
        - 'schema'
        - 'value'
      loop_control:
        loop_var: 'varname'
